Import Pandas Module and Printing Top 15 Books

In [124]:
import pandas as pd

df = pd.read_csv("final_output.csv")
df.head(15)

C:\Users\tapan\AppData\Local\Temp\ipykernel_2164\3252439433.py:3: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("final_output.csv")

,user_id,book_id,rating,title,author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Location,Age
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,"tyler, texas, usa",NaN
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,"seattle, washington, usa",NaN
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,"h, new south wales, australia",16.0
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,"rijeka, n/a, croatia",16.0
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,"rijeka, n/a, croatia",16.0
5,276733,2080674722,0,Les Particules Elementaires,Michel Houellebecq,1998,Flammarion,http://images.amazon.com/images/P/2080674722.0...,http://images.amazon.com/images/P/2080674722.0...,http://images.amazon.com/images/P/2080674722.0...,"paris, n/a, france",37.0
6,276744,038550120X,7,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...,"torrance, california, usa",NaN
7,276746,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,"fort worth, ,",NaN
8,276746,0449006522,0,Manhattan Hunt Club,JOHN SAUL,2002,Ballantine Books,http://images.amazon.com/images/P/0449006522.0...,http://images.amazon.com/images/P/0449006522.0...,http://images.amazon.com/images/P/0449006522.0...,"fort worth, ,",NaN
9,276746,0553561618,0,Dark Paradise,TAMI HOAG,1994,Bantam,http://images.amazon.com/images/P/0553561618.0...,http://images.amazon.com/images/P/0553561618.0...,http://images.amazon.com/images/P/0553561618.0...,"fort worth, ,",NaN
10,276746,055356451X,0,Night Sins,TAMI HOAG,1995,Bantam,http://images.amazon.com/images/P/055356451X.0...,http://images.amazon.com/images/P/055356451X.0...,http://images.amazon.com/images/P/055356451X.0...,"fort worth, ,",NaN
11,276746,0786013990,0,At the Edge,David Dun,2002,Pinnacle Books,http://images.amazon.com/images/P/0786013990.0...,http://images.amazon.com/images/P/0786013990.0...,http://images.amazon.com/images/P/0786013990.0...,"fort worth, ,",NaN
12,276746,0786014512,0,Make Them Cry,Kevin O'Brien,2002,Pinnacle Books,http://images.amazon.com/images/P/0786014512.0...,http://images.amazon.com/images/P/0786014512.0...,http://images.amazon.com/images/P/0786014512.0...,"fort worth, ,",NaN
13,276747,0060517794,9,Little Altars Everywhere,Rebecca Wells,2003,HarperTorch,http://images.amazon.com/images/P/0060517794.0...,http://images.amazon.com/images/P/0060517794.0...,http://images.amazon.com/images/P/0060517794.0...,"iowa city, iowa, usa",25.0
14,276747,0451192001,0,How Stella Got Her Groove Back,Terry McMillan,1997,Signet Book,http://images.amazon.com/images/P/0451192001.0...,http://images.amazon.com/images/P/0451192001.0...,http://images.amazon.com/images/P/0451192001.0...,"iowa city, iowa, usa",25.0

Taking A Specific Columns And print The df

In [125]:
df = df[['title', 'author', 'rating']]
df

,title,author,rating
0,Flesh Tones: A Novel,M. J. Rose,0
1,Rites of Passage,Judith Rae,5
2,The Notebook,Nicholas Sparks,0
3,Help!: Level 1,Philip Prowse,3
4,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,6
...,...,...,...
1031131,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,0
1031132,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,9
1031133,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,0
1031134,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,10
1031135,Fourth Grade Rats,Jerry Spinelli,10

Merging the Existing Columns into New Columns

In [126]:
df['tag'] = df['title']+ " " +df['author']
df

,title,author,rating,tag
0,Flesh Tones: A Novel,M. J. Rose,0,Flesh Tones: A Novel M. J. Rose
1,Rites of Passage,Judith Rae,5,Rites of Passage Judith Rae
2,The Notebook,Nicholas Sparks,0,The Notebook Nicholas Sparks
3,Help!: Level 1,Philip Prowse,3,Help!: Level 1 Philip Prowse
4,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,6,The Amsterdam Connection : Level 4 (Cambridge ...
...,...,...,...,...
1031131,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,0,Edgar Cayce on the Akashic Records: The Book o...
1031132,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,9,Get Clark Smart : The Ultimate Guide for the S...
1031133,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,0,Eight Weeks to Optimum Health: A Proven Progra...
1031134,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,10,The Sherbrooke Bride (Bride Trilogy (Paperback...
1031135,Fourth Grade Rats,Jerry Spinelli,10,Fourth Grade Rats Jerry Spinelli

Cleaning The Data

In [127]:
df = df.dropna()
df = df.drop_duplicates(subset=['title', 'author'])
df = df.reset_index(drop=True)

Convert Text into vectors

In [128]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=7000, stop_words='english')
vector = vectorizer.fit_transform(df['tag'])

Find the index existing position from the title columns

In [129]:
from sklearn.metrics.pairwise import cosine_similarity


idx = df[df['title'] == "The Notebook"].index[0]

Find the similarity of number of vectors and creating the list and enumerate the scores to get data in tuple and reverse sorted to get higest similarity to lowest similarity

In [130]:
scores = cosine_similarity(vector[idx], vector).flatten()
scores = list(enumerate(scores))
scores = sorted(scores, reverse=True, key=lambda x:x[1])

it gives the index position and return the book name

In [131]:
# try and error method i did

scores = scores[1:10]
idx_value = []

for i in scores:
    idx_value.append(i[0])


df.iloc[idx_value].title

167773    The Notebook (Gemstar)
45417       UN Cuore in Silenzio
2629          A Bend in the Road
19555                The Wedding
8618          Nights in Rodanthe
7489                  The Rescue
2883                The Guardian
3021                  Icy Sparks
20903                 Icy Sparks
Name: title, dtype: str

In [ ]:
def recommend(book_name: str):
    # convert it into lower letters
    
    book_name = book_name.lower()
    
    # from the title col convert the small letter and check if the title is ==  to the book name
    matches = df[df['title'].str.lower() == book_name]
     
    # It checks the white space and check the wrong book name example -> harry pttr, not in dataset
    if matches.empty:
        print("Sorry but we can't find your Book please give another book for recomendation")
        return

    
        
    # get the index value
    idx = matches.index[0]

    # get the similarity vector
    scores = cosine_similarity(vector[idx], vector).flatten()

    # convert it list and enumerate the scores
    scores = list(enumerate(scores))

    # sort the scores in descending order
    scores = sorted(scores, reverse=True, key=lambda x:x[1])
    # Give the top 14 books
    scores = scores[1:15]

    # checks the dataset is empty or not if yes then pass this block of code
    if len(scores) == 0:
        print("Sorry we can't Recommend the book")
        return
    
    # give the index value for iteration
    idx_value = []

    # using loop i and append to the blank list
    for i in scores:
        idx_value.append(i[0])

    # Give top books name
    top_books = df.iloc[idx_value]
    # give the data by rating which highly rated by the user 
    final_output = top_books.sort_values(by='rating', ascending=False).head(5)
    
    # return the final_output
    return final_output[['title', 'rating']]
     
    
#  give the book name
book_name = input("Enter your book name you want to read: ")

# call the function
recommend(book_name)

Sorry but we can't find your Book please give another book for recomendation